- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
    homebrew_packages:
      - { name: python }
      - { name: ansible }
      - { name: git }
      - { name: wget }
      - { name: curl }
      - { name: tree }
      - { name: nkf }
      - { name: go }
      - { name: ruby-build }
    homebrew_cask_packages:
      - { name: firefox }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: sourcetree }
      - { name: atom }
      - { name: intellij-idea }
      - { name: vagrant }
#     gem_packages:
#      - { name: fastlane }


  tasks:
    - name: リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    
    # gem
#    - name: gemによるインストール
#      gem: name={{ item }} state={{ item.state|default('latest') }}
#      with_items: gem_packages
#      register: gem_result
#    - name: gem パッケージの情報保存先ディレクトリを作成
#      file: path=gem_info state=directory
#    - name: gem パッケージの情報を保存
#      shell: gem list | grep {{ item }} > gem_info/{{ item }}
#      with_items: gem_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list 

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

