- name: パッケージをインストール
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: homebrew_packages
  register: brew_result
  when:
    - homebrew_packages is defined
    - homebrew_packages | length > 0

- name: パッケージの情報保存先ディレクトリを作成
  file: path=brew_info state=directory
  when:
    - brew_result is defined
    - brew_result.results | length > 0

- name: パッケージの情報を保存
  shell: brew info {{ item }} > {{ info }}/{{ role_name }}/brew_info/{{ item }}
  with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
  when:
    - brew_result is defined
    - brew_result.results | length > 0
