- name: homebrew-cask のインストール
  homebrew: name=brew-cask state=latest

- name: cask パッケージをインストール
  homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
  with_items: homebrew_cask_packages
  register: cask_result
  when:
    - homebrew_cask_packages is defined
    - homebrew_cask_packages | length > 0

- name: cask パッケージの情報保存先ディレクトリを作成
  file: path=cask_info state=directory
  when:
    - cask_result is defined
    - cask_result.results | length > 0

- name: cask パッケージの情報を保存
  shell: brew cask info {{ item }} > {{ info }}/{{ role_name }}/cask_info/{{ item }}
  with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
  when:
    - cask_result is defined
    - cask_result.results | length > 0
