- name: gemによるインストール
  gem: >
    name={{ item.name }}
    state={{ item.state|default('latest') }}
  with_items: gem_packages
  register: gem_result
  when:
    - gem_packages is defined
    - gem_packages | length > 0

- name: gem パッケージの情報保存先ディレクトリを作成
  file: path=gem_info state=directory
  when:
    - gem_result is defined
    - gem_result | length > 0

- name: gem パッケージの情報を保存
  shell: gem list | grep {{ item }} > {{ info }}/{{ role_name }}/gem_info/{{ item }}
  with_items: gem_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
  sudo: yes
  when:
    - gem_result is defined
    - gem_result | length > 0
