- name: setting bash_profile for rbenv
  shell: |
    echo '# path for rbenv' >> ~/.bash_profile
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo '¥n' >> ~/.bash_profile
    echo '# execute rbenv init' >> ~/.bash_profile
    echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
    source ~/.bash_profile
